name: dragons_down_randomizer
description: "Randomizer for Dragons Down board game"
publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^10.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true